import pickle

songList = [
("Holy Ghost","A$AP Rocky","6AHNkRbVzkh95xilnYzDT7"),
("Canal St.","A$AP Rocky","0rBMP6VVGRgwnzZCLpijyl"),
("Fine Whine","A$AP Rocky","2WxzLbJfPA2vJGxQiKd7Jq"),
("L$D","A$AP Rocky","4S7YHmlWwfwArgd8LfSPud"),
("Excuse Me","A$AP Rocky","3I8MbKRkS2IBDuslhCS3iT"),
("JD","A$AP Rocky","6wwPtKxaMEbQYc6atQmhTE"),
("Lord Pretty Flacko Jodye 2 (LPFJ2)","A$AP Rocky","1j6kDJttn6wbVyMaM42Nxm"),
("Electric Body","A$AP Rocky","6br4Pc0BzU6dTD5fEmks2i"),
("Jukebox Joints","A$AP Rocky","2gAGWaK4wvt2xrFUlR4mK8"),
("Max B","A$AP Rocky","4wuOxtRDeD9YiQOcmgay7e"),
("Pharsyde","A$AP Rocky","6J9FgTr3z44Bw6ABeVL415"),
("Wavybone","A$AP Rocky","5cYZm4KeDKM8Pw8z5XRKJt"),
("West Side Highway","A$AP Rocky","3RySVukMPe4R7lAP8oGI17"),
("Better Things","A$AP Rocky","3nHbQNMuGuEtIVhPGVfFbF"),
("M'$","A$AP Rocky","29ZSk6XmWPx3DX69xBb7Yi"),
("Dreams (Interlude)","A$AP Rocky","2JqNypbkqPNtCLBeuUqmnm"),
("Everyday","A$AP Rocky","2N3U8uTYhjX2KwGT0pf5x0"),
("Back Home","A$AP Rocky","41FxRrhwqe2LvFcU3WapS1"),
("Water","Ra Ra Riot","1spp1NXsz4rHcVaJhhndKa"),
("Dance With Me","Ra Ra Riot","482nc1OVq3aK12gyW0Y6fV"),
("O My Heart","Mother Mother","47nPb8z39sIDBPjL7az706"),
("Burning Pile","Mother Mother","2vPcxNVTD4SBjf2hnIi6Jv"),
("Body Of Years","Mother Mother","23bbkcQn2xZ9RXfTWY9lmK"),
("Try To Change","Mother Mother","1zDfRonK0SNPe0tYUT1riP"),
("Wisdom","Mother Mother","5LUApV986u6vRvDqujsjhq"),
("Body","Mother Mother","3UFnjqDaLc6WMtvE1UrXek"),
("Ghosting","Mother Mother","6405hOm4Nxfxzm2wxXw2BU"),
("Hayloft","Mother Mother","2ZPw5uyVI5m1nSvjQYmf3j"),
("Wrecking Ball","Mother Mother","1VZo1zddq6LpxwMtvHPVgM"),
("Arms Tonite","Mother Mother","5THPJToPbXswRx9sn498iB"),
("Miles","Mother Mother","2eiEk13k4S9VWQULJuy7eh"),
("Sleep Awake","Mother Mother","0R4gTLjqxdaUYydq74UXpF"),
("Neighbors","J. Cole","0utlOiJy2weVl9WTkcEWHy"),
("Earthquake - Full Version","Labrinth","3SxiAdI8dP9AaaEz1Z24mn"),
("Sherane a.k.a Master Splinter’s Daughter","Kendrick Lamar","0qGFnxDIqGBIq2D3zNbjk9"),
("Bitch, Don’t Kill My Vibe","Kendrick Lamar","712uvW1Vezq8WpQi38v2L9"),
("Backseat Freestyle","Kendrick Lamar","3aGibUHhQyBsyumYHylw0K"),
("The Art of Peer Pressure","Kendrick Lamar","0d0jsoba88SpOoFxCxA2rZ"),
("Money Trees","Kendrick Lamar","0AOvNRgl0SMfOibWA5bP8o"),
("Poetic Justice","Kendrick Lamar","2P3SLxeQHPqh8qKB6gtJY2"),
("good kid","Kendrick Lamar","5vuJuBqwzHJgCA1ysRfwxZ"),
("m.A.A.d city","Kendrick Lamar","2cDCojn6uIBM6A5xTAbl3H"),
("Swimming Pools (Drank) - Extended Version","Kendrick Lamar","5ujh1I7NZH5agbwf7Hp8Hc"),
("Sing About Me, I'm Dying Of Thirst","Kendrick Lamar","3q2v8QaTnHLveAQzR6gvYm"),
("Real","Kendrick Lamar","5d8yMIlqJH78lwOUP7T3oF"),
("Compton","Kendrick Lamar","1wf4LnpdAhLaoI2WwYDKAE"),
("The Recipe - Bonus Track","Kendrick Lamar","1eRBW1HcyM1zPlxO26cScZ"),
("Black Boy Fly - Bonus Track","Kendrick Lamar","1H7yy9jlDYS2EBF41J6Yf5"),
("Now Or Never - Bonus Track","Kendrick Lamar","4KjnaUNYPwGnJjoeTFlt91"),
("The Recipe (Black Hippy Remix) - Bonus Track","Kendrick Lamar","5UHjWOJA6MDl1g3x2HC68V"),
("Bitch, Don’t Kill My Vibe - Remix","Kendrick Lamar","7ALEBJ8LOQqXVJ2tqnXtoH"),
("F*ck Your Ethnicity","Kendrick Lamar","5v501hmUMvbHPKa7qm0MGD"),
("Hol' Up","Kendrick Lamar","5DO1SazQppcsKQ1c1JpyQz"),
("A.D.H.D","Kendrick Lamar","2MYl0er3UZ1RlKwRb5LODh"),
("No Make-Up (Her Vice)","Kendrick Lamar","7yQDLdub1VuUUwbpteUX7w"),
("Tammy's Song (Her Evils)","Kendrick Lamar","3RPK9VQuTsiTySY48ldeqx"),
("Chapter Six","Kendrick Lamar","3s3ZBjw8kKX5HXymkRIDVy"),
("Ronald Reagan Era","Kendrick Lamar","3gl1RenSXn1biKijZ1qvky"),
("Poe Mans Dreams (His Vice)","Kendrick Lamar","2NxIp9jbmsnaIiAExWOEo0"),
("The Spiteful Chant","Kendrick Lamar","12bCgkFnyyTI8B1OmmRhbx"),
("Chapter Ten","Kendrick Lamar","2C1C4QjjMmru4mYrPSQzWs"),
("Keisha's Song (Her Pain)","Kendrick Lamar","0bcCgRudYZ4kiOHZNZfqxU"),
("Rigamortus","Kendrick Lamar","2b3KgzISdjZVNPJJ1945nw"),
("Kush & Corinthians","Kendrick Lamar","705u4LfXcTBuDOB8UCy0A7"),
("Blow My High (Members Only)","Kendrick Lamar","6jl01C724Mk68qlOQLco5I"),
("Ab-Souls Outro","Kendrick Lamar","2FTGmG9PvlXEERkb1sYBE3"),
("HiiiPower","Kendrick Lamar","4fVqQKbROkz8Z9FFJS7vls"),
("Disco Pogo - Atzen Musik Mix","Various Artists","175TGA4MS0ikF27KGmdjaL"),
("Ulf ist Kult","Mosh36","2JVOxVSRdFMUBmFywiQ8s1"),
("Martinshorn","Nate57","2U4veScEFVryqx7nw2igNd"),
("Gangsta","ScHoolboy Q","2dUkCUXXoknwsLwuGaL4bA"),
("Los Awesome","ScHoolboy Q","7sycKW6BGv7eTXVdtWkqom"),
("What They Want","ScHoolboy Q","3p2x3UD9wz9yt3gtftKwT0"),
("Hoover Street","ScHoolboy Q","4fUeGY1jGkgtx11tuqbDlq"),
("Studio","ScHoolboy Q","29gsi1zZrZxdStACmTQB0Z"),
("Prescription/Oxymoron","ScHoolboy Q","3ljBzccXOpkHcGejRzHVjK"),
("The Purge","ScHoolboy Q","1oQJ26nHHgHh45WqyA59GF"),
("Blind Threats","ScHoolboy Q","3BKLZpsKsymeFquQWUjhGx"),
("Hell Of A Night","ScHoolboy Q","5DOR49R0fehoBmyNL8m4sN"),
("Break The Bank","ScHoolboy Q","5rk3EqsP1iHuQn5tkC1Qw0"),
("Man Of The Year","ScHoolboy Q","5SsR3wtCOafDmZgvIdRhSm"),
("His & Her Fiend","ScHoolboy Q","6RhRGitp1UtVOvboboXq2A"),
("Grooveline Pt. 2","ScHoolboy Q","1eQ6ky8AGbsKIZe2wXKauq"),
("Fuck LA","ScHoolboy Q","68Sxbmub4GZAF48w49CZDA"),
("Collard Greens","ScHoolboy Q","0zO8ctW0UiuOefR87OeJOZ"),
("Just What I Am","Kid Cudi","4LoMziEaxdkrSMXtavIJqL"),
("Hallelujah","Logic","7fRfIvHPH6bHdMDjPFwTMh"),
("Everybody","Logic","7cGFbx7MP0H23iHZTZpqMM"),
("Confess","Logic","58kwvMXeOlsvzPqUlyj75Y"),
("Killing Spree","Logic","6OQea06z3cbOqYgG2O6eOZ"),
("Take It Back","Logic","6HN5XPJEV31RQJGoyqZ81K"),
("America","Logic","77mLzdHEWRB60CLlV02TV2"),
("Ink Blot","Logic","732btJLGu7gYNHHNdzshrG"),
("Mos Definitely","Logic","53LkLW4k4w7EOayzvx70O9"),
("Waiting Room","Logic","4GP2Idcs08NqAjfEV0rsl6"),
("1-800-273-8255","Logic","5tz69p7tJuGPeMGwNTxYuV"),
("Anziety","Logic","6CvTbrBxxc5jFwqsivhpxh"),
("Black SpiderMan","Logic","7BKUWh5sdtdS17crohRe4L"),
("AfricAryaN","Logic","76ZrqdtkKxhMl42xAQTnFm"),
("Contact","Logic","2M5ndhTi0zOIymTD4Ff1T8"),
("Fade Away","Logic","4QRWA5UqYU1st9aO0UfxOj"),
("Upgrade","Logic","5psz20rVFNRlt0u9cpzBpY"),
("White People - Scene","Logic","7Li7ff5lQ1gqvwbCdRXaQL"),
("Like Woah","Logic","6bM3GKo47KVgvj3gHdWS0U"),
("Young Jesus","Logic","0KiKfllNTmhImvXVIHqR0z"),
("Innermission","Logic","1zucHJN4WKHIzSL4FyiJw9"),
("I Am The Greatest","Logic","1BTj47Up5m8601KOFrTvkj"),
("The Cube - Scene","Logic","30S46V7RcyGXUModoqW69b"),
("Lord Willin'","Logic","4q6oNFTjZmJqkIgPdp8iR1"),
("City Of Stars","Logic","5mJbSgVBnJ4ayOjFdmyOdl"),
("Stainless","Logic","5rwOE5J3Y1A2NiRa6y3Yph"),
("Babel - Scene","Logic","58RqurG6pfsJVxNyc9OL22"),
("Paradise","Logic","0M2ZekrsEkru9Xp5rWnouQ"),
("Never Been","Logic","0aAk9KMmPChiS2EG9Fg7IX"),
("Run It","Logic","4iq3zHwgHSxstFvYw4yIsQ"),
("Lucidity - Scene","Logic","1sQBStJC5unqE7TzStlFQl"),
("The Incredible True Story","Logic","5FhaG2uuOPmPcGXO9aniCH"),
("Intro","Logic","3RyT0M0ZVETTPFIWPiFL0x"),
("Soul Food","Logic","4gKTgPgFEttvPSzHA8EOo3"),
("I'm Gone","Logic","0P1wH403SZCVHRrHzdSAUu"),
("Gang Related","Logic","5SiH1JfdmqgWrK6BHBjbCX"),
("Buried Alive","Logic","73JNvc6jFSZkx4R84kyPzL"),
("Bounce","Logic","3bA1iq8gddrg5DvgyqdXD5"),
("Growing Pains III","Logic","7w97IYlna881b8oOnzckg0"),
("Never Enough","Logic","02FgozogtnZghe8DtBeUAt"),
("Metropolis","Logic","3QSQMtxZLxMIhRxeDqgSvj"),
("Nikki","Logic","5g8bR5hEuANnazd1mnLq05"),
("Under Pressure","Logic","2JEqqPu4UYnzcNxDy9JVu3"),
("Till The End","Logic","2mRh9gO4YlLJo6vFRgT13V"),
("Run the Jewels","Run The Jewels","1iMsfRdEDePb1ybyM7Wter"),
("Banana Clipper (feat. Big Boi)","Run The Jewels","4JeQKkqHge23LL68N1sZJT"),
("Ddfh","Run The Jewels","7vAPdj763w31JAjcDW7Q2r"),
("Sea Legs","Run The Jewels","3lhVpxpMfgXfUNVBIOwdBG"),
("Job Well Done (feat. Until The Ribbon Breaks)","Run The Jewels","3ZuzKPMGnok1Jeun0mtxBH"),
("No Come Down","Run The Jewels","1EDvpHHqzz5j7W9yrg3lkM"),
("Get It","Run The Jewels","1rU7n8ZVGbIprbunBky72s"),
("Twin Hype Back (feat. Prince Paul as Chest Rockwell)","Run The Jewels","6fZE73k3vhW4xYTOpdwaQM"),
("A Christmas Fucking Miracle","Run The Jewels","59fKNCUMTncSMICMNqT2in"),
("Best Day Ever","Mac Miller","2jeWxoYEARpy0lGGahsKd5"),
("Get Up","Mac Miller","2I5tgzOlFMAxcmcxh7tpUg"),
("Donald Trump","Mac Miller","2e0PQjgRNMDKeaMH49tHnC"),
("Oy Vey","Mac Miller","7B3chUwV6zZFOpgbVJ3SgS"),
("I'll Be There","Mac Miller","6eLtze68aoRMmcOnl8uyxC"),
("Wear My Hat","Mac Miller","21pL3UtIn5uqJ9hXCrSSw4"),
("Wake Up","Mac Miller","2TLqO1WFm6FJPf9L6lgG5b"),
("All Around The World","Mac Miller","4SBED4EYaEdY8mgLF9gcOm"),
("Down The Rabbit Hole","Mac Miller","3NXhty3B7HBhf5lDmMYBJm"),
("In The Air","Mac Miller","5aajOwnbxqJf5MKArXo5kY"),
("Play Ya Cards","Mac Miller","4MXzDuCfbsXAnHGxYFGk3j"),
("She Said","Mac Miller","4pi0ViyUMFiVtVQo06bXdq"),
("Life Ain't Easy","Mac Miller","1WW3DftAMN2IYIQU5Lqtwd"),
("Snooze","Mac Miller","3CetU5jnLMht8fCQzJ7ZN9"),
("Keep Floatin'","Mac Miller","5wH3ShFsOvrNCNtHF7sitB"),
("BDE Bonus","Mac Miller","653FhwnB8YXSwqbuPn8eB4"),
("Outside","Childish Gambino","2VtpdevRsfoxtWlnVm1l8A"),
("Fire Fly","Childish Gambino","06WD650Zt5MQ55kFMP2f3r"),
("Bonfire","Childish Gambino","4zGvb8hxGLB2jEPRFiRRqw"),
("All The Shine","Childish Gambino","2ZBr6a8ecFqLJA0lcvFPCc"),
("Letter Home","Childish Gambino","076K8Jg7xmjCMn816yZboV"),
("Heartbeat","Childish Gambino","3HooZZPp0evFShqaJ2Pwer"),
("Backpackers","Childish Gambino","03ImchswSXPA2KzLrc9hAL"),
("LES","Childish Gambino","2KMCM2dirSnthfYKNjS8iT"),
("Hold You Down","Childish Gambino","4wv0lOxuHGbnLXVBFmxfxy"),
("Kids","Childish Gambino","3z1eL3iolJSdiYEEodX1k0"),
("You See Me","Childish Gambino","1eEPKr5gzWVSZKiMWIMZYa"),
("Sunrise","Childish Gambino","5hMxgvMmI99alD8JJpjO0w"),
("That Power","Childish Gambino","6O8iT490HuTFVjQo3eHdoi"),
("illuminatro","Logic","0cdXG7PwSUOv19gF6dMv5n"),
("Flexicution","Logic","2c8sgbZoEanC3QyFNZxUcA"),
("The Jam","Logic","4dVJyyeCPEONr44NIrXvie"),
("Slave II","Logic","4Mr73gFwZUeFnrfRov23we"),
("A Word From Our Sponsor","Logic","1AdD7pFBsQICMHiQTz9uwV"),
("Wrist","Logic","7qT7NUDywO7vNJNTNxqWiN"),
("Super Mario World","Logic","1py4qzrEEkOvU8uTHYLuOW"),
("Studio Ambience At Night: Malibu","Logic","7mfLCMIvu0cZVNpvdXEVT5"),
("44 Bars","Logic","4s2BWgnSQ9NZiOQM4PP4HB"),
("Slave","Logic","3SrUV8pxnW1QhMbbwegpwG"),
("Deeper Than Money","Logic","6pK86Tx0QqX0E64mKuDB5Q"),
("Dropjaw","WHY?","003Y3lZgRonimqbHQkJezU"),
("Start A Party","Rae Sremmurd","6vFpwoagZKaQveINvGrbFK"),
("Real Chill","Rae Sremmurd","1pF3VcWYHeuVPflRwGBaWV"),
("By Chance","Rae Sremmurd","3eaZlarqKQ4oAceRwJHfF5"),
("Look Alive","Rae Sremmurd","2IGr3q6ljcpLvHDFLtI0yW"),
("Shake It Fast","Rae Sremmurd","10UJwHwGSXnljKk4Nw3qrf"),
("Set The Roof","Rae Sremmurd","634enyZhLpXIvwqCPQr3Lt"),
("Came A Long Way","Rae Sremmurd","66XG9rHaNSXiOzDnpyePbL"),
("Now That I Know","Rae Sremmurd","79fZYYQkY4U8rMiomn7xw5"),
("Take It Or Leave It","Rae Sremmurd","6kRctUEvX9wU9Jp2rMrXgr"),
("Do Yoga","Rae Sremmurd","0Ic9AMmXhdk7l53KmTqdFO"),
("Over Here","Rae Sremmurd","6RnOIETETowFGyW39Zuil4"),
("Swang","Rae Sremmurd","6mapJIPnQ23RTAevUoE0DL"),
("Just Like Us","Rae Sremmurd","1A4sbcpfCNyGM88NtGkSqD"),
("Wait","E-Dubble","18tk1g5Du0zNnizsx9vchy"),
("Golden Ones","E-Dubble","0dhGrSSv3G649VIE4e6wk2"),
("One Question","E-Dubble","6rr9Bd7I5tOEQ8k2U9adg8"),
("War of Attrition","E-Dubble","3KePMi1q91SbXuvQcejSdD"),
("Heat (Five OHH)","E-Dubble","0T5feckrw8ZpkbeRLn00fC"),
("Waves","E-Dubble","1c0UxrUxaBfRgBzPVCb4jj"),
("Olly Olly (Oxen Free)","E-Dubble","4AYgCANwsbAqipPVB6MRQq"),
("Getting By (I'm Good)","E-Dubble","2PFiweJkTIvMObKS8qNnct"),
("Graceland","E-Dubble","7DILFglOWPgze58wc5c6Qk"),
("Two Tone Rebel","E-Dubble","43kQu3PTBhCZCNhzaufAaX"),
("Black Beatles","Rae Sremmurd","6fujklziTHa8uoM5OQSfIo"),
("Hip-Hop Is Good","E-Dubble","5nKGo2HcJTKhS1GPPYs9gt"),
("Alive Til' I Die","E-Dubble","182ahgmbp7AFghXs4RKdu8"),
("In The Bag","E-Dubble","17vx9ffZklz5cYusViK3AF"),
("Nest","E-Dubble","1xumhft7bYd6EGr3odlixH"),
("The Dude","E-Dubble","7GUdsmshAVTYqXU8f9mnZX"),
("Robots, Pop Songs","E-Dubble","1ojEeK6qTnQyZTqsFM5j6u"),
("Drinking With My Headphones On","E-Dubble","0XND3SA4Cg5lPdcD0OS2F0"),
("Dogface Go","E-Dubble","7FrnloCDHVWyYl4ruTdXMH"),
("Don't Like My Music","E-Dubble","1qBnB3Mt0YFX8sxbWT3kvU"),
("Karaoke Night","E-Dubble","3Qaofc4BnP05bmWgttghp3"),
("Jambox","E-Dubble","4ARpOs50k1lgoprUMpuSYq"),
("No Time","E-Dubble","3HtIeUUzLUE8cEtKjskWkX"),
("Miracle","E-Dubble","74FjBNtz3PXXZZJrXWwRrm"),
("Reset","E-Dubble","33UEF9B8giFxjECI2mk8CE"),
("Down","E-Dubble","3MZmqc9exvKqVnTTjMYlRg"),
("Code Words","E-Dubble","0ztwkfcvbouOuOOqGnHp3a"),
("For Future Reference","E-Dubble","27dQKTUTTxhMERFx2lkqoz"),
("Cycle of Nightmares (Let It Go)","E-Dubble","3ECQXaH8c1hQb8fZAcrNoV"),
("Running With Blades","E-Dubble","0IPPuP3A6m97oOC5e2Qhwt"),
("Coming of Age","E-Dubble","1aMX40ZlCtuYnAIdNLR1jH"),
("The Library - Intro","Childish Gambino","2jQIzjFeqCT3jOUi3dIlWB"),
("I.Crawl","Childish Gambino","2peoIrd4v8r4HXNPXePIXQ"),
("II. Worldstar","Childish Gambino","4oRqSiVyGrwb8dnJBO6FNu"),
("Dial up","Childish Gambino","5Bn2fo4Ri8ikJXmpiQBoL3"),
("I. The Worst Guys","Childish Gambino","7pRcWov3NHxi0GDkKdbSb0"),
("II. Shadows","Childish Gambino","2uMMGgkTOBisJpzyvMzNWm"),
("IV. Sweatpants","Childish Gambino","2rmq49FcJ4U3wh1Z7C9UxE"),
("3005","Childish Gambino","3Z2sglqDj1rDRMF5x0Sz2R"),
("Playing Around Before The Party Starts","Childish Gambino","2DxKSe9ZWmZUXGdbXCcPET"),
("I. The Party","Childish Gambino","4raEiDlfGu9dgeOfqldy0b"),
("II. No Exit","Childish Gambino","3ebRmYrOYceH3NNowFoZVn"),
("Death By Numbers","Childish Gambino","7JSdsfOoM8ueAuqPOrjc4T"),
("I. Flight Of The Navigator","Childish Gambino","2XSKbNkH4EeuvoOs8dliBH"),
("II. Zealots Of Stockholm [Free Information]","Childish Gambino","6vy95NfrMeUfaXpaTm4O53"),
("III. Urn","Childish Gambino","2UOAaxhSOWDgSaIWYeoaJk"),
("I. Pink Toes","Childish Gambino","2D5Dd3clzZGTv6H9mtAAQq"),
("II. Earth: The Oldest Computer (The Last Night)","Childish Gambino","5WCuoYligCr05q99p5D50S"),
("III. Life: The Biggest Troll [Andrew Auernheimer]","Childish Gambino","4hZ9MbRJoxzDhx5WJlnDIA"),
("The Vowels Pt. 2","WHY?","2wNC44mmKAr9ICB2ySE7vS"),
("Good Friday","WHY?","0Pcolnl2MxmjPSl4ZMSpWc"),
("These Few Presidents","WHY?","0njyKLS01B9YG6BwnFcVIV"),
("The Hollows","WHY?","0aam9MBtezX1g9GfmUaxOQ"),
("Song of the Sad Assassin","WHY?","1W8goupeWSAg5jMW2Hy1aR"),
("Gnashville","WHY?","0FyRGY0mxpaNIfEOSLB3ga"),
("Fatalist Palmistry","WHY?","01rgZI4xYSpyp4EFrdcS5E"),
("The Fall of Mr. Fifths","WHY?","7CIn5N3CTP6aM9rnbx8Kh1"),
("Brook & Waxing","WHY?","6FzOvWJGooDbTUjd0elUWZ"),
("A Sky for Shoeing Horses Under","WHY?","0XNU64GfN5nCJFGxvvGEDx"),
("Twenty Eight","WHY?","7pasPT8iKdf1RpGImLC7uL"),
("Simeon's Dilemma","WHY?","0IOcR8CGEemjipYCAL3gn6"),
("By Torpedo or Crohn's","WHY?","5NmcKJl9et0tbzQ4F61cEu"),
("Exegesis","WHY?","0twlyMJ96V1SQtgpWIYh0V"),
("Doll","Foo Fighters","2KvhVhBR7MIMZUQNRBiY2k"),
("Monkey Wrench","Foo Fighters","44wXefe8WB9Fd6xwtmAwbR"),
("Hey, Johnny Park!","Foo Fighters","0M5xRyxGpFFDfzN2x0wdpH"),
("My Poor Brain","Foo Fighters","3yIUusX4NApzRSAkxZFrJg"),
("Wind Up","Foo Fighters","56ucsSaTrjiQaokbbDASOR"),
("Up In Arms","Foo Fighters","05TcC5ZN9rp8Glx8A9C2Nd"),
("My Hero","Foo Fighters","4dVbhS6OiYvFikshyaQaCN"),
("See You","Foo Fighters","48PrL49eJ5P15yTxjK0oW6"),
("Enough Space","Foo Fighters","4JWRyetq4ALHAXm9ByOOEg"),
("February Stars","Foo Fighters","2ceA7CWWx6yIHdzppN8nLF"),
("Everlong","Foo Fighters","5UWwZ5lm5PKu6eKsHAGxOk"),
("Walking After You","Foo Fighters","7pS2OVdIWviLpz5GOtJLzz"),
("New Way Home","Foo Fighters","44yHNmayqe7dI9fHjAYPCl"),
("The Colour And The Shape","Foo Fighters","4ZnD7qmpP3NWA1ctUzeUIw"),
("Ophelia","The Lumineers","3d8y0t70g7hw2FOWl9Z4Fm"),
("Purple Heart - Bonus Track","I Am Giant","1G33RQfvBLk7Xk4Gs4XwlR"),
("City Limits - Bonus Track","I Am Giant","4TZeWHDKaSeEFCAkd6X1ib"),
("Let It Go - Bonus Track","I Am Giant","2dUd5jmV7MqEAPSdDtcXYI"),
("Escape Artist","I Am Giant","0h5C2rFeFCD1infAed6cqZ"),
("Electric Throne","I Am Giant","5O7nrOBaAVXauZp32VOss9"),
("And We'll Defy","I Am Giant","6n5OukRk1HqsDLT7iRGw9R"),
("Bodies in the River Nile","I Am Giant","1090JsTapMW2MqKKkGmDFm"),
("Neon Sunrise - Bonus Track","I Am Giant","5DqVehS1AIw6IVq8yuj0sD"),
("Black Hole of My Heart","I Am Giant","23Lxp64KTPmpfOqbZRpkuq"),
("Nightvision","I Am Giant","6cjwVH69SXc7pr659xfw9M"),
("Drag My Name Through the Mud","I Am Giant","3ZRGzbVIUM6rvwFahZkLgE"),
("The Haunting of Elinor Shaw","I Am Giant","4n4kUACGOY2GR5OJLdPwk5"),
("Living the Crash - Bonus Track","I Am Giant","6zGgEcRdtEKgViU3JaNi3l"),
("After the War","I Am Giant","1TWKNF0wVslZoXev4mnhjq"),
("DUELE EL CORAZON - Remix","Enrique Iglesias","7CnDrJ3mlKBEcAUVAlzUQE"),
("Speak to Me","Pink Floyd","574y1r7o2tRA009FW0LE7v"),
("Breathe (In the Air)","Pink Floyd","2ctvdKmETyOzPb2GiJJT53"),
("On the Run","Pink Floyd","73OIUNKRi2y24Cu9cOLrzM"),
("Time","Pink Floyd","3TO7bbrUKrOSPGRTB5MeCz"),
("The Great Gig in the Sky","Pink Floyd","2TjdnqlpwOjhijHCwHCP2d"),
("Money","Pink Floyd","0vFOzaXqZHahrZp6enQwQb"),
("Us and Them","Pink Floyd","1TKTiKp3zbNgrBH2IwSwIx"),
("Any Colour You Like","Pink Floyd","6FBPOJLxUZEair6x4kLDhf"),
("Brain Damage","Pink Floyd","05uGBKRCuePsf43Hfm0JwX"),
("Eclipse","Pink Floyd","1tDWVeCR9oWGX8d5J9rswk"),
("In the Flesh?","Pink Floyd","24YmWQgunJGAU8El3ndkyn"),
("The Thin Ice","Pink Floyd","62zuXt6X5B6YQOBNFV2eXG"),
("Another Brick in the Wall, Pt. 1","Pink Floyd","7K6xMPtAjTuLPNlJMLf5bS"),
("The Happiest Days of Our Lives","Pink Floyd","2O3l4X1yTua8oMMCtazkyo"),
("Another Brick in the Wall, Pt. 2","Pink Floyd","4gMgiXfqyzZLMhsksGmbQV"),
("Mother","Pink Floyd","1GEOSS415bZVHNuXWlCT6b"),
("Goodbye Blue Sky","Pink Floyd","0ESdtt9cjGZUkUbaubSrv2"),
("Empty Spaces","Pink Floyd","5yMyLZu4wPvWcbLFiRhYVM"),
("Young Lust","Pink Floyd","3xGJuHvSxFJxxYlHj5BIoT"),
("One of My Turns","Pink Floyd","66YHxyGAUGjMBDdrDlWIMD"),
("Don't Leave Me Now","Pink Floyd","3QEWEv1tvHmVgsT5THpGDn"),
("Another Brick in the Wall, Pt. 3","Pink Floyd","5A7eooPKJHtr0UJmatjH4a"),
("Goodbye Cruel World","Pink Floyd","0ZXkKRO789QKBR6ME7pIDF"),
("Hey You","Pink Floyd","7F02x6EKYIQV3VcTaTm7oN"),
("Is There Anybody Out There?","Pink Floyd","5HAjss9faCAowGY8dM24r6"),
("Nobody Home","Pink Floyd","2gTnu5RZNVFVnWdjLnyUA5"),
("Vera","Pink Floyd","7FCiDC7ojdm19CJePq6QAe"),
("Bring the Boys Back Home","Pink Floyd","4TUStFzBGQqn0GrkzVWFV4"),
("Comfortably Numb","Pink Floyd","5HNCy40Ni5BZJFw1TKzRsC"),
("The Show Must Go On","Pink Floyd","077OhUjy58qkjscrXjW696"),
("In the Flesh","Pink Floyd","5OFi9CIyD6s1oENyHapK2W"),
("Run Like Hell","Pink Floyd","0EaLRxrtnq7Mqhdf8q9txr"),
("Waiting for the Worms","Pink Floyd","2DVkYfl2YuOMlRfC98srEG"),
("Stop","Pink Floyd","21L1dVOTGhvAKvBXXnTIHj"),
("The Trial","Pink Floyd","1UMXtudajhlocMzXVSngDU"),
("Outside the Wall","Pink Floyd","1nW0lHGLpE1iQDP5Nvt3x1"),
("The State Of Massachusetts","Dropkick Murphys","4g9aB6nGJxQA1ZHtzAXirL"),
("Rose Tattoo","Dropkick Murphys","4bLKGUkVRxIyrN1770DdDm"),
("Vagabonds","Satellite Stories","6yAJPb8dxpPGfTZjSdo2Db"),
("Heartbeat","Satellite Stories","4BUsGK6bAzCul8PId6ghC1"),
("Polarized","Satellite Stories","0dwCRxDNqXWExIkNjR0vuZ"),
("Campus","Satellite Stories","50CHxk70ntOqlqljLy45il"),
("Heroine","Satellite Stories","4G8zHuQqPrYfYLIXvNwjuY"),
("When Love Became","Satellite Stories","4Xoyvf9BwyhJWuCP1lT4b6"),
("Painted Arms","Satellite Stories","62JruqMLbuOhItXj8pgWv3"),
("Round and Round","Satellite Stories","4xG2dhqpNp2BXnLDshB60k"),
("Same Sun","Satellite Stories","5Qi54SgmCo8y2lArA0Vbsk"),
("The Trap","Satellite Stories","0kTXtk7NSe3OzQ4FDonwyO"),
("With You","Satellite Stories","4yMyXyv1kuFV522wTILydo"),


("Dan Bilzerian","T-Pain","5QfQKhvdcxPgp68O0S39FV"),
("Love On The Brain","Rihanna","2aksifNn5ph8igDOkPBA02"),
("Ab Ovo","Joep Beving","02mkkozonPEDCenOhuWwLc"),
("You Used To Say (Holy Fuck)","The Front Bottoms","3KPp825w9niuNqzXu9AgQ4"),
("Peace Sign","The Front Bottoms","7BTfCCOitwPLJLlgPMpz1g"),
("Vacation Town","The Front Bottoms","7kTIsaswz1ord7QA9HDE4U"),
("Don't Fill Up On Chips","The Front Bottoms","4bAfcaNPjsqAUU0Edu6R6U"),
("Grand Finale","The Front Bottoms","4wQXk1y3jEKbHL98H7WCo5"),
("Trampoline","The Front Bottoms","6MSb9ZuAw0hGPeTFrEpOjP"),
("Raining","The Front Bottoms","4YyOPaXcxCmpv3c7SQUo5e"),
("Far Drive","The Front Bottoms","2W3aQvHX1vvZq5MHGHG1ID"),
("Everyone But You","The Front Bottoms","2sVUc3mmHmI575Unlj3S1q"),
("Ocean","The Front Bottoms","5woK5a239IHU1hMOIk4Umn"),
("Bae","The Front Bottoms","1WQFJRfWvVNs8T7jl4QxW7"),
("Michigan","Ed Prosek","4NOUuDnWzbSukaI89WkXiR"),
("Say Wassup","Travis Thompson","33scMKy1UPU1JkjnwiDgOh"),
("Scott Pilgrim V. My Gpa","Mom Jeans.","0hBMssKd1e2FLXM46XaXJb"),
("The Girl","Run River North","6GntglmlmgQ8iPCDN1FcYC"),
("Masks (Live)","The Brook & The Bluff","5I0DzPPBMW46NUXRm8wmwC"),
("Underground","Cody Fry","3xfgaFFYLZtgDdzW7UlWwW"),
("Native Tongue","Quinn XCII","77dEtUAHufvPJLZkwaj2Vu"),
("Love Letter To Myself (I Will Love)","Ocean Pleasant","1QdQuRt9PxLAWnJKiHkl0C"),
("Stranger","Covey","1kiffDo2l26ladtXDMHiI7"),
("Ukulele Song","Jackal & the Wind","3hjd9Xa8U5S3zPfHAjiQJo"),
("Cocaine Jesus","Rainbow Kitten Surprise","0ZAbupc7jAQpG9IxojQ3s3"),
("D.A.N.C.E.","Justice","2hQCzcb3qyZirWzOD5Yzoj"),
("Raining","The Front Bottoms","1YUls5UWI9Gz4QQqkqm3hR"),
("Vacation Town","The Front Bottoms","7mAl6XhDiYifjVH9Rjocrq"),
("Oh Heart","Tank and The Bangas","6kjf54SjPLNsxbHVpIYq56"),
("Tell Her","Rizzle Kicks","5dmGaUgmzBiVeSqKu01xFd"),
("Dying to Meet You","She's Only Sixteen","3JDo2GzmISfn1eJhxjUfNO"),
("Home Alone","Ansel Elgort","6He0K0vTMdPdbweh18nnrB"),
("Bad Habits","The Federal Empire","3IMBsqHL48Eu4K3uvhRIok"),
("You","Manwolves","6F7CjVIrwk7PddQUsoPmoo"),
("Talk to the Moon","Ripe","5vKRk56FvQuEzw0g9Ng8do"),
("Sour Candy","Melt","5gRCBF8BbbQA4M7wRFjqxg"),
("Common Ground","Busty and the Bass","5KUesgd9NtLrG8v1hbbhFL"),
("Black Bear","Black Bear","7kS4JyQvrqssb5DmDMwqOC"),
("Lies","Skrizzly Adams","2mo1oG04YZ20OmCiaB0Z35"),
("Chapter Three: The Great American Game","Levi The Poet","3mtBECrW2PA9NQcCOMsJJH"),
("Where I'm Coming From","Bronze Radio Return","60SV7HSk7dwgIDvVCi7Ru0"),
("Don't Be Nice","Watsky","0tuE3l1TPJ9tKG4w63kgtf"),
("Sorry Charlie","Emeryld","1cKCVE0Od5OuoyXBLCsHLT"),
("DNA.","Kendrick Lamar","6HZILIRieu8S0iqY8kIKhj"),
("Hurt (Quiet)","Nine Inch Nails","7c7xbd5LqwBjdutg8di7IJ"),
("Don't Look Back In Anger - Remastered","Oasis","7CVYxHq1L0Z4G84jTDS6Jl"),
("I Don't Know","Jon D","3uCHI1gfOUL5j5swEh0TcH"),
("Carry Your Heart","Wildermiss","3bBwwD63i86ztOqnTS6p3U"),
("Horses (with PnB Rock, Kodak Black & A Boogie Wit da Hoodie)","PnB Rock","5de7ci7TFqbQ1PFgKAD7MR"),
("Nights Like This","Emilio Rojas","2GpfKrNFmY3VyzYWZADrtC"),
("Finest Girl (Bin Laden Song)","The Lonely Island","1LpjlPR8Gv52B04UQNLZAw"),
("Sim Ayin Aleynu","Hatikva 6","3l6wHX0PfwEazuO6oEqNs8"),
("The '59 Sound","The Gaslight Anthem","6sAbdRWPf9lsSDbXVgmdwG"),
("The 59th Street Bridge Song","Simon & Garfunkel","0eGl5p2TAYt76pqjEvQPa2"),
("The Night They Drove Old Dixie Down - 2000 - Remaster","The Band","2x0supcZhd6NEH1nem9DnR"),
("Open Your Eyes","STRFKR","0xxm1WskKZSCvbkGjkSMr2"),
("Invincible","Big Wild","5EBZGhW4OSo6mS8B3STM3X"),
("עוד פעם פעם","Hatikva 6","0bklngIW2WD4ygW4dIXbAP"),
("Post To Be (feat. Chris Brown & Jhene Aiko)","Omarion","0fgZUSa7D7aVvv3GfO0A1n"),
("Try Me","DeJ Loaf","2CY92qejUrhyPUASawNVRr"),
("Good Lovin","Ludacris","60BVxPevV4Jr3Dj4M7Md0z"),
("Be Nice To Me","The Front Bottoms","5dyUA8LLCsPPD9xTtE4XKz"),
("Angels","Khalid","67kXYrMTQbS7MVbXyGyxHm"),
("Broad Shoulders (feat. Chance the Rapper)","Taylor Bennett","6m3ZXs465Rt4Tc1iiLktXL"),
("No More Bad Days","This Wild Life","6P5aQRuHdeQqqfFOU74JsB"),
("Stick to Your Guns","Watsky","5qGNpxkebY7iqN6i46dDma"),
("(Bonus Track) Exquisite Corpse","Watsky","6G64UdPdlraaVuLzhoXlrH"),
("Rock Ring Park (feat. Watsky & Herbal T)","Elements of Music","0FuNdpset5ucMtC8bg6rBP"),
("Where's Your Heart Gone (Simlish Version)","Golden Youth","2nNgB4HV5Q1MugwVFMUPZZ"),
("Wildfire","Seafret","2Ro9FLIVhPwIQopSr48oJT"),
("Stereo","The Jepettos","5C6bSqr1yycedel0VKiUTt"),
("Moscow","Autoheart","4ylE1Sl2wohbCvToD1fHsl"),
("Happiness Is Not A Place","The Wind and The Wave","63iSkVYY8Qv8pMrIRyT1ES"),
("Ava","Famy","05YoWLFjHU9qc4tXcCqtLW"),
("Wolves and the Water","Edward R.","59jyjMxUustKCD6nYHfyEC"),
("Carry","Branches","7A7RloGKD4wjKYktZBOFXf"),
("Yours to Keep","Jordan Mackampa","0ljxKa4x3ahmDeQOrLCjJr"),
("Weight Of It All","Handsome Ghost","3YW7AWZMCvNBYBPoFdebTh"),
("Found","Seramic","7pgnqCLy19mBLFPdQcs9pm"),
("Suit And Jacket","Judah & the Lion","2ZYBwkmtYhgUj1A7teYAZ7"),
("Lou Lou","Albin Lee Meldau","44bVPjVJXl3eKayZGLvh0a"),
("Please Notice","Christian Akridge","36seMHoyXmLUNxcwzwjdF7"),
("Ego Loss On Grand River Avenue","Joe Hertler","7qgj6nsXFnuLmvbpacMeBw"),
("Flannel","The Cardboard Swords","0NdcwnhSMhJbHR82PgTZ5S"),
("6 Foot 7 Foot","Lil Wayne","0z5ZPs57J2KERwM1tBM2GF"),
("Oh Brother","Saint Raymond","4VBZbQw57uAtXTtwPBMYm2"),
("Welcome To Your Life","Grouplove","6uF5q1IM4nXjh4Hw3pY4Cw"),
("Same Drugs","MisterWives","6CTTipcCa8RZX8aY0mttHa"),
("Goodmorning","Bleachers","1K13OsIMc0HLgEJHZoWH78"),
("Glitter & Gold","Barns Courtney","1aJtyIMev4kW8IMUxOjn1Y"),
("Sour Patch Kids - Acoustic Redux","Bryce Vine","3VL2I21M04Nz08LnVBfNaD"),
("Sick of Losing Soulmates","dodie","4hjbxjZpJ8H6qRCzDOGI0M"),
("The Men That Drive Me Places","Ben Rector","0DrIEgXGCctCqzHUihq2t2"),
("Machine","Scott Helman","5bd7amccz6nBtODT3TgAZE"),
("Nowhere to Run","My Brothers And I","60PnzoOkiK690YrM9Wlhrj"),
("Hope","Christian Akridge","2k3Wyq6QP81TQLzk0fu9WH"),
("My Jumper","Joe Mungovan","4oUgBkextwzf2F8SYMtTYJ"),
("Don't","The Stairwells","3Kz0F9vXaVRhr8KE8X1Do5"),
("Pursuit Of Happiness - Extended Steve Aoki Remix (Explicit)","Kid Cudi","5PX4uS1LqlWEPL69phPVQQ"),
("drugs","EDEN","3OXpdrHLT4IqM76RajgM6Q"),
("Lay By Me","firekid","5HUynLdprJzINndFXcidfu"),
("Oh No","Lawrence","263GRw6nywFGES3vTu0jFx"),
("Run Right Back","Moon Taxi","6TmUM3aMNJqC47QSbH61bN"),
("Swim Good","Gavin Castleton","0RXzJgQPsDUC51mzpgQ8w5"),
("Put On","Jeezy","5dANgSy7v091dhiPnEXNrf"),
("Oracle","Timmy Trumpet","2IavT15tYiFl0WCHMJ8HUM"),
("Live The Night","W&W","4GwXdVLueKZ8YhYjZmWtYh"),
("Drink","The Happy Fits","4YDbjd5K0tNntyeWg0HSY8"),
("Our Apartment","Aaron West & The Roaring Twenties","3uoQIZiEENqa7yEObOSakx"),
("Rainy Girl","Andrew McMahon in the Wilderness","42tEPGKhxm0te2QJ8B5lOT"),
("About Today","The National","33xh6sgYhga7iQ7HARN7V6"),
("I Wander","Isaw","4nkxs37mnCz1jCDgemJTWv"),
("Brass Not Rash","The Gotobeds","0L8yowlcBoaIWcEtXPFyTY"),
("Twinkling Lights","Annalise Emerick","2lxbM6i5Hykn7vDRrL7wdA"),
("Give Our Hearts Some Weight","Joel Ansett","4bLQhLyDNfsySUQbxkICxE"),
("Two of Us on the Run","Lucius","25FoplCa9QqSc8ohE6gzAs"),
("In the Dark","Matt Woods","3eHumvv1LTzCwtFUJKF09v"),
("Redshift","Darwin Deez","439ue6BnErB9MfHMU9zIio"),
("South","Hippo Campus","64TjzuxG5PJ7payjphrOC0"),
("Elise","The Greeting Committee","6gjUxk2gNqaMtTYV0t3PPB"),
("The Ocean Song","Joe Probert","0rHBlqw1liZCgdilTTN3lq"),
("She Lit a Fire","Lord Huron","0zCckv4tx3KzJ5GGTRbbLf"),
("Warriors","Too Many Zooz","4keKh92BlOnRSEBeumCPM4"),
("Silver Lining","Rilo Kiley","0ieqq1wbtso2UjJWPqJ5Xc"),
("Between the Bars","Elliott Smith","7BhZDvzJV21Dd5bY9xvtII"),
("Good Time","Leroy","5LkS6nrZ4It0f3d0CegeAn"),
("Without You","Oh Wonder","0IVHlst3XMgzXUJbIyZ8oO"),
("Leaving, on a Jet Plane","John Denver","1qYsHkUBFSRrGEQqkogO6U"),
("High Hopes","Kodaline","5rZXBHUU2qz7huEckTwpqo"),
("Open","Rhye","3JsA2sWDNR9oQogGAzqqtH"),
("Give Me Love","Ed Sheeran","0SuG9kyzGRpDqrCWtgD6Lq"),
("Nakamarra (feat. Q-Tip)","Hiatus Kaiyote","12v5GBM74fB8WsHJPQRTIe"),
("Gold Rush - Deluxe Edition","Ed Sheeran","4mT5mVFaU7trA3UdbGqfB9"),
("Hey Mami","Sylvan Esso","4gB5Idv1iw8jgxyEvuwPVA"),
("Superman","Lazlo Bane","19nAFg6Mb6jXN3yxPC2sSk"),
("iSpy (feat. Lil Yachty)","KYLE","2EEeOnHehOozLq4aS0n6SL"),
("It Won't Kill Ya","The Chainsmokers","5xhJmd0I15jFcEdqxfCzKk"),
("Stay (with Alessia Cara)","Zedd","6uBhi9gBXWjanegOb2Phh0"),
("Last Day Alive","The Chainsmokers","6GeD5g9vZTz25Egf8kxoIY"),
("Honest","The Chainsmokers","6KjbNLbRjuoa8rEq5yNA6H"),
("If We Go Now","Moulins","5r8qxTxwF3TvbXdfOkObl5"),
("Always and Forever","Pat Metheny","4mg3FP3BP4ELno3sCfjToL"),
("Pristine","Mantaraybryn","52ug4BzkXF06EkVX8axf8y"),
("Nicely Done","Wild Party","0cLWwUbcScGETTnMR5Qngp"),
("Ultralight Beam","Local Natives","3wAW1vIrWxUmJajU9tl0AP"),
("West Coast","Hey Marseilles","6JrhK1EuBS9EKpFmcuhrp1"),
("Sunny December","Bombadil","1VXyZc3zfYb1nSsjSHcDT7"),
("Arizona","Frances Cone","7hGeRC8nVfXI4a9sC8x8N7"),
("Ars Poetica","M&O","6dKVhp692aB0ISAPTq1Dug"),
("(No One Knows Me) Like the Piano","Sampha","5zOnoB8FdZudDcPX4O8WqF"),
("i was all over her","salvia palth","7svpAkwc6xaSxlbZ7V7JiS"),
("Liability","Lorde","6Kkt27YmFyIFrcX3QXFi2o"),
("Cry Baby","Dukes of Daville","0wyJ29sfrx810ZqbdDBr4n"),
("Dead Oaks","Now, Now","5uV1a9IZ7IW2zdYfBSrfF2"),
("When the Storm Is Near","Ostrea Lake","0F9IrckTzYyKv6sZlFeqhx"),
("I Love You","Benjy Davis Project","3qDUJ5FQpEMvfg1ihGEWkR"),
("Kids Again","Artist Vs Poet","0b1kU7KgZSnH7n7TBy921o"),
("Les amants","Édith Piaf","3JXGUlE8ngIjTsKXSiuo0a"),
("Closer","Scott Bradlee's Postmodern Jukebox","0E32W7S52AaR4ht7i7DwDq"),
("Blank Space","Ryan Adams","7363P58oxh8jr5NEv7086t"),
("Carried Away","Dionysia","0wUoZywSfSu4QppV2uEYCt"),
("Running from My Savior","Wolfie's Just Fine","0r9G6zwLkEXN93X3Y6bR9C"),
("Big Casino","Hot Mulligan","2h12jkyFDWWZHtYNvkAMtB"),
("Andante cantabile (arr. from String Quartet No. 1)","Various Artists","3i8auRQaMorXGYwHbfwpye"),
("The Light","Phantom Sage","1xwSxInQXyvD3VypBfcslf"),
("Joanie","The Front Bottoms","5INWlwa21TSPLA7SdIE9YS"),
("Munny Right","Jon Bellion","28pdIEbChDEj6JdhAuuXU9"),
("80's Films","Jon Bellion","4hiqs3SbbbxA7LvcHtp9mI"),
("Hand Of God - Outro","Jon Bellion","6ej9jEXBeQI7PTbx68KHfi"),
("Luxury","Jon Bellion","5CgFGKdTn8R5dXGEPEX6Gm"),
("Rivers and Roads","The Head and the Heart","4Q6Kuze3wNMQRjamyBjHUR"),
("Hey Mama","Great Caesar","5KlVIOeSrcVTZoasODK3W5"),
("Countdown","Sondre Lerche","37eN6ZWb7AKkObti06ShAs"),
("Coraline - Other Father Song","Chris Morton","2hlEY1tXhAUqFeboU54j5A"),
("Manchester","Kishi Bashi","2R6SthKPxZO1EdqLBXWOwA"),
("Boy","John Mark Nelson","7Hc1dKzCDzVqvlI8XaMZwH"),
("Only","RY X","6cQtwdaYskE6c1IyihSMTA"),
("By the Ocean","Kid Indigo","4LHppyZnQrqM3aqELbeIFA"),
("Perfect Strangers","Jonas Blue","1Te8WIfLudxjHTr66BL0JK"),
("I Try (Living Room Session)","Busty and the Bass","5Ak1WawJtN2sTijFZoKQEJ"),
("Naked","X Ambassadors","3qHzSBZ4gVVZZmV3XB089s"),
("June, After Dark","Elliot Root","1nSWQ5Y7OcuGiWGdA1UYlr"),
("Next Year - RAC Remix","Two Door Cinema Club","5SL5AexE9va7cP6s0B9E4m"),
("Worth It","Moses Sumney","0eLkNPumzKxZED8L44g2G3"),
("Everlasting Sigh","Moses Sumney","3139p7lHnPboMeNt739bbv"),
("Measurements","James Blake","16NlVqvSoCnApLpASSUpLU"),
("Plastic","Moses Sumney","57K5RyWj4jOlc07wRz6axh"),
("Thank You","Bombadil","34a295RioFNNKHqfRi3eVd"),
("When You Love Someone - Acoustic","James TW","6668ZaUUXqZ25Tb0DMr2HO"),
("'Bout It (feat. Daniel James & Benjamin O)","Jeremy Zucker","0AIL1m3mlMi98wKOaJ7uoG"),
("Lights And Camera","Yuna","6i56WJgLrdfAKEEN55uR5o"),
("Don't Let Me Down - Hardwell & Sephyx Remix","The Chainsmokers","1JI70l1lE5IF2tgJm5TnMD"),
("Too Much Time Together","San Cisco","0LcVvD1iPjqkfVdWd7ClfA"),
("She Only Loves Me When I'm There","Ball Park Music","67B7OO0arS3XIZ74UQjp5e"),
("Magnolia","Gang of Youths","5Y2EJAT1iMR5IujvILuNPG"),
("Guilt Trip","PUP","76YqPiiWWyngCU72YTY1tx"),
("7 Years","Lukas Graham","5kqIPrATaCc2LqxVWzQGbk"),
("The Future","Mustered Courage","1NuPZeWYa1Owb7zYcAI2vt"),
("Flying Kites","Jeremy Zucker","0yjdEwkPYbhCXN6uCedpVu"),
("Fuck It and Whatever","The Echo-Friendly","4o9CzuuK6x4R1Qh0NyxCc9"),
("Funeral Beds","The Districts","2I3D1f3jdWVojq4RK2Eqa3"),
("Punks and Poets","Elliot Root","15arhZdjyxnf4vgUTwTP7n"),
("Gale Song","The Lumineers","5rCHluRq4hQTOB8A3IvgC9"),
("I'll Be Fine","Buster Moe","21ZTHHYPQ8iHAnuKn4ZXlM"),
("Annabelle","The Ghost of Paul Revere","2l5zeirtwESfygzUXirOke"),
("Your Graduation","Modern Baseball","2J1t2b8xPBqZzj5znx0C7C"),
("Above The Clouds Of Pompeii","Bear's Den","723paR6LrVISFCXFPf5z57"),
("Anthem","Alana Yorke","0q5VKbAXqMZeusj49g86oQ"),
("Little Bird","Hollow Wood","39xzTyul2F0ExCu0z4Igbo"),
("Gold","Death Team","3YidSwVRBoBPfL3nvC0vJA"),
("Fuckin' Problems","Xavier Dunn","2GNfQXXBfJUj0NsuDd9Tmc"),
("In the Yard","Del Water Gap","0RTffAzvOiPIeuTZdbpRsN"),
("Hollywood","Tobias Jesso Jr.","5jwAj4lq7bmac48652kX2C"),
("Ophelia","The Lumineers","3qhobDAfBcVoOWZP8Ck8R2"),
("All I Want","Kodaline","2PwXOevGUSkU8qaYZjgLq2"),
("Somebody Else","The 1975","5hc71nKsUgtwQ3z52KEKQk"),
("Dessert - Remix","Dawin","2mqDi8BzmNw54qrVHduyiu"),
("Once In a While","Timeflies","6cREm4bV7V79Yxdilx9HDo"),
("All My Friends","Snakehips","6TaqooOXAEcijL6G1AWS2K"),
("Gold","Kiiara","6ZSO7kPn8IMJFymyticbJO"),
("Don't Let Me Down","The Chainsmokers","1i1fxkWeaMmKEB4T7zqbzK"),
("Night Still Comes","Neko Case","0l5TOyEd5RswsWnqOaOX0X"),
("Dancing With Fire (feat. Stalking Gia)","Boombox Cartel","4UciArpih1UoflaDFRGtlZ"),
("Fast Car","Jonas Blue","2mCF8L0brIs88eH6Kf2h9p"),
("Lost In The Light","Bahamas","25J4d78ESH2MgAJoIakB8O"),
("Lost in My Mind","The Head and the Heart","3gvAGvbMCRvVDDp8ZaIPV5"),
("She Burns","Foy Vance","3rUw4cRDeYVZhjkUXBnFUQ"),
("Don't Mind","Kent Jones","27PmvZoffODNFW2p7ehZTQ"),
("Better Off","Emily Vaughn","7jEYdiDSaJ0UhJYvxnCImo"),
("Darling (feat. Missio)","Said the Sky","5CrxyHP494lmFlLCOdiva8"),
("Insane","Flume","13xCqDPPQqLIQhe4QmZZRu"),
("Say It (feat. Tove Lo)","Flume","217xrcrbBtgJhvlHicxTSH"),
("In Too Deep","Sum 41","1HNE2PX70ztbEl6MLxrpNL"),
("Caroline","Jon Foreman","1ZFw1rrEG1v0iWRkABvw85"),
("Animal","Javier Dunn","1HnDHi1KZrsMSwGut1A8KC"),
("Getting Easier","Portage","3kxucV5Vdtjzaj5brAKKEX"),
("Secret","Flearoy","4PmhYS3x1JrTe7BFgUmKKB"),
("Sleep Please Come to Me","Matthew Barber","5o24dov2RmOgxsWmvbE0N0"),
("Things Happen","Dawes","2SYvX2G6D5SD6BpijIOBpG"),
("Brother In The Night (OurVinyl Sessions)","The Weeks","2nYqpuX5O4PpirH1Fn0Rsj"),
("Never Come Back Again","Austin Plaine","4yRlTvPVfEyhXfp6GZurq9"),
("Inspiring Song","Chillout Lounge","2fcK2nnCdaQPLHspJobgWe"),
("Ballad of the 20th Maine","The Ghost of Paul Revere","7uERgVWW7R7H6kw3QJKzzg"),
("The Struggle","Scroobius Pip","4OuXxJMxmTwIplxJO8MBCi"),
("Gold Teeth (feat. Flux Pavilion)","Dan Le Sac vs Scroobius Pip","02RypIvFAy8Lm7N2ogWUrg"),
("Float On","Ben Lee","3OMDCi4JyMwyj7dLzaMIfb"),
("Maddy Brown","My Brothers And I","1pxV0DY4TrhKU4LImyZfzs"),
("You and I","Johnnyswim","4fxNwAXn8J9LNi5Rz8eMIv"),
("House of Winston","Shakey Graves","76A9aKOUxNAtnJ7Jp9fKGa"),
("Devil Like Me","Rainbow Kitten Surprise","0HsGh7cboYz6cVMIyFrQ8j"),
("Beach House","The Cave Singers","6wNSTqC9pspZMCJLUx1ia6"),
("Tuck the Darkness In","Bowerbirds","0FrCdLSwmmmu3iUxfj2VbZ"),
("Drain You","Horse Feathers","0yfnDB052TSfaoH6jJsUhl"),
("With You","Roméo Testa","5Sktn4wgfqMe9RmN0P0AYy"),
("Southern Sun","Boy & Bear","40ttk439NA9RvbLBJpJU1M"),
("Amadeus","Family and Friends","4F9jpNQDKRFoyM4Ebpni6S"),
("Dearly Departed (feat. Esmé Patterson)","Shakey Graves","0ewrI06EIDMGXvgJxuyF3U"),
("Sedona","Houndmouth","2kG5litgxXvx6ZRgwO1v7W"),
("Tear In My Heart","Twenty One Pilots","3bnVBN67NBEzedqQuWrpP4"),
("Sonsick","San Fermin","5Y8NV8AiYPodmq6uOYflq6"),
("Powerlines","The Western States Motel","1WxEB0ho6l8rWbxTNORBpA"),
("Arcadia","The Kite String Tangle","30AeH6saju8WPJo73cKZyH"),
("We're All Young Together","Walter Martin","5o1jHl6tDNUNNwevJKudua"),
("Jack and Blow","Atta Boy","1WRxtvHH4GwqOvH0b3HTII"),
("Back Before We Were Brittle","Say Hi","0nGhmP2Fj4ybr9uQCJppwg"),
("Come Away","Handsome and Gretyl","5Zeiw8jeN2GFB6TjEaVlZE"),
("Carry You","The Native Sibling","2WjRDrYPcD89PRi1NwyWvC"),
("Run!","M&O","1EimiqOx4xsHf4d51denJI"),
("Hour Glass","Little India","76dUI1PcPnsixELy7UL0Ie"),
("Mistakes Like This","Prelow","4telT9zZWgv4d8gD4WZrlA"),
("Make Our Own Way","Little Brutes","5RZZ0nZHC6mrKdzoPgsG3P"),
("Shorty Don't Wait","A Great Big World","33caYRuBFGkI5JaFMUeydz"),
("In the Summer","IAMDYNAMITE","3yyC2DElwp9KzkqeaTsFb8"),
("Trees to Stone","Fremont","2PIOI3qJcLLtf9sG1MVblX"),
("Born Again","Josh Garrels","68nNNThyOXq060K1ZAWb2t"),
("Hands Down","The Greeting Committee","0dqJjKKxuKD5Dt3QH2n4CG"),
("Stayin' Alive","Cereus Bright","3UhbF2H7ykGAmfOwQH4LBT"),
("Be Your Last","Emily Reid","0u7KTAfcJfGnp7EDmjK1LR"),
("That's What's Up","Lennon & Maisy","5cmvTvxqKFhr7U5sjNQ7Ce"),
("Sirens","The Weepies","7aJosrOo3mKYTGnPZywrWJ"),
("Get up, Get On","Jill Andrews","48mhRAnKkpLVuMmqTMPBUe"),
("Bitter Water","The Oh Hellos","7xwOCSKispEfJOlZHW08R2"),
("The Heart","NEEDTOBREATHE","2gNRPDHT9jw2fIKLRpLgT9"),
("More Than Life","Whitley","1Db3RDS6mdsuD5ibO7Bo1F"),
("Even the Darkness Has Arms","The Barr Brothers","6W49z468BT75GsO2tCcBtq"),
("Morocco","Moon Taxi","30lgD1UuHczwlxa7NZFeSQ"),
("Modern Times","Zaac Pick","3hAtgZ1MKyyfpRwOIWktYO"),
("Pick a Place and Read","Ezra Bell","3P2q1CHk8hVmu1IXjr8Us4"),
("Here Tonight","Sam Burchfield","6ItGPha13j36IiQlvubGrT"),
("Roses","Alonzo Holt","28Ohm88opgWkWQPnrbskl2"),
("Little Ballerina","Emile Haynie","2Zc88UXIORcnvHHeJNRd1b"),
("After Many Miles","The Ghost of Paul Revere","1yLENA7X3q7xVEk57UjXY7"),
("Sweet Emotion","The Kooks","0hIGUS1PQbv5NIrHIf6Fza"),
("Mexico","The Staves","6x7oPOBrfsqx9WbON5X1go"),
("Let's Get Started","Dylan Gardner","0mGeaxNzBIm0vMNjxKX5Xs"),
("Kansas City","The New Basement Tapes","2JTBNz8VZx7i38pcPROWuz"),
("Venice","The Lighthouse And The Whaler","15KUDgDxvkghmtB6FxI7Dt"),
("Another Night On Mars","The Maine","3oe574OaDVi0qyTyk8PNaX"),
("Amy's Friend","Bombadil","7JCFtmI2WKlY7VxDe7SmNC"),
("Lemons","Woodlock","6cD0FXdVYxbUBab9nnaov0"),
("The Muse","The Wood Brothers","2eEj2cIxdU4wm47z7UBMIC"),
("All Is Well","Austin Basham","700xxgbIpH0YNMideY7sWR"),
("Budding Trees","Nahko and Medicine for the People","3E3I7DBGCIsIgT1a1UJEFK"),
("Gedicht","Nico Suave","75AS5lIRyYuTTiX3ETmI6m"),
("Gone","The Show Ponies","5xZV3jkOFbKLH7ywEqGORA"),
("Mykonos","Fleet Foxes","18ycL9Q5zLDeY9M2Lr3Ozw"),
("Pumpin Blood - Acoustic","NONONO","6sVk7yGOUuFjXte9kTV1JL"),
("Pierre","Ryn Weaver","31c1V9xUONZYk78NE4Id8D"),
("One And Only","Teitur","6RSuk4OQYdXJEIwwagQ1mT"),
("Zombie","Jamie T","0e7055c3hWGd47Xkvzoj4H"),
("Fred Astaire","San Cisco","59CzyyXjbOfTxfsv5MnBOV"),
("Sunday Candy","Donnie Trumpet & The Social Experiment","6fTdcGsjxlAD9PSkoPaLMX"),
("Reality Dream","Morning Parade","6IbODNRImkWKzzpddXR1u5"),
("Edge of Desire","John Mayer","5gbxzSqABThINGDb7vIiwe"),
("Gotta Have You","The Weepies","0YNNfiKJb4yqUDtCcX1cHK"),
("What a Good Woman Does","Joy Williams","3IkOMz5Y9dHzV71vsqAuNS"),
("Poison & Wine","The Civil Wars","3wsZYuHJrk3lssa7V7jvye"),
("Bottom Of The River","Delta Rae","2LzyUfJdRp3uqTrITBJXEY"),
("I Saw You Blink","Stornoway","4mT2VI23PYyHCVZAtoOMo3"),
("Drop The Game","Flume","150zGw0P2EJccYJKnFIler"),
("Overcome (feat. Potato Potato)","Tora","2cJ0Gx3vlB5WWFnJUlNG0A"),
("Changing Of The Seasons","Two Door Cinema Club","6gLQrU5bvwPf6BTlCSO6x2"),
("Crystals","Of Monsters and Men","5wU6jk9kxYzFGUpeE6T2Q5"),
("Blood","The Middle East","13yuX1iqobZtQtq5lr8UoC"),
("A Little Bit Of Everything","Dawes","5UDEGEbvqFwrzT2P2PcJ27"),
("Say It, Just Say It","The Mowgli's","2J3n32GeLmMjwuAzyhcSNe"),
("Keep Your Head Up","Ben Howard","5fpEDGQX0Ah3utGnFYulQZ"),
("When I Get Older","Wild Party","4NOZKKJKMWhQCe5uyQNNG6"),
("Television","You Won't","7HLTfpgbqC85BayqViMHmU"),
("Coming Down","Ball Park Music","5sBHxH826qCNBJGDlrLYFt"),
("Mango","Catey Shaw","36aNtkLkN0a2mBg5W9uBVP"),
("Don't Ask Me Why","Great Caesar","06QdJtEtHOckzHhq5EbTfo"),
("Open Season","High Highs","6XPC7ZNTJcnWzQaLZYe3od"),
("Slow Motion","PHOX","0gqysuo5JAFi4J1chidYzK"),
("Hello My Old Heart","The Oh Hellos","2c62Xf5Po1YSa1N6LOjPHy"),
("Weekend","Priory","0cj9hVVRrYqLfAgaWnTnSx"),
("Hold On","The Gospel Whiskey Runners","5dr2wzx5W8nOwg94jhSL6U"),
("Hands Down (Demo)","The Greeting Committee","0TvMonYsxZeIKh4cIdP7O7"),
("Wait for Me","Motopony","5SHOb5hvMDzmIRfDhwBoq5"),
("We're On Our Way","Radical Face","2hWLWMEIyDdHwdnn6f4VtU"),
("Just Kids","Mat Kearney","0IONkFDQMwLq1cXgzgniFR"),
("Escape Artist","The Zolas","5i3EeNLoy5JQT8XbHroY8p"),
("Cold Moon","The Zolas","4V8GMJ68wAcATONXUC5TtA"),
("Anna Sun - Live From Spotify NYC","WALK THE MOON","3Syg4GwsW6yFeTbZUqWvYS"),
("Abc","Alexander Fairchild","6AGbQEjzAzqLaZlqlONpeW"),
("Then Came the Morning","The Lone Bellow","5bIOaGjf4RuPoBMTt5DkqC"),
("Pristine","Mantaraybryn","6esJxlVjN4EqxN9GSxX4uz"),
("Keep Together","Hunter Hunted","6wdzLY3TTwx7zVnMmj8Z8R"),
("Wait so Long","Trampled By Turtles","1QesQ27kCWYTYuXJi8SApS"),
("Colour Me In Gold","JP Cooper","2r9ub1K7V4PrLRsIA665nS"),
("Unaware","Allen Stone","7uYLvVRrr2KI3dlW5YcXNR"),
("Zorbing","Stornoway","7mGfYYr2IbYzk0oBWSxeWO"),
("Olivia","Rayland Baxter","0HNhfGGE2n702ieqFxQV5M"),
("Baby I'm Yours","Arctic Monkeys","6FLqFu1ApSkUddZ9P4H6Io"),
("Lucky","Kat Edmonson","5w7iocU90UMdRQaOwNzpAp"),
("Alienation","Morning Parade","54Jan0Hqp63H3X1XZdNP5a"),
("Switzerland","The Last Bison","3PuKf5pn248yPymkQdcaeT"),
("All We Have Is Now","The Modern Electric","5s78vi4v2Qo95QbPGTWKE2"),
("Submarines","The Lumineers","6TWPAG7Oam1mdut6Ov77qh"),
("A Summer Song","Conner Youngblood","2ro7C9SAg54fL7ribZOt1j"),
("Candles","Daughter","1zZcEoMG3ZEUU6hEPyPXh5"),
("Soulfight","The Revivalists","3TQxkQsyJS03EUwl02Qaub"),
("I Can't Wait","Star & Micey","5VEDbBjTdi5G2pWJqIIucu"),
("Road Regrets","Dan Mangan","2mS00gZ64Vlqcqp1pwRQwZ"),
("Since Last Wednesday","Highasakite","6KZZJRfUyjsbpNo01oag8X"),
("If It Wasn't for You","Various Cruelties","0jNHnzfNig0x2YByaskWJI"),
("Stella","Cereus Bright","32yiDCLJUdqYoaDR46z9gD"),
("You & I","Jacob Whitesides","0FbWwsocYl5VpO76nfZdUX"),
("Bow And Arrow","Reuben And The Dark","7FvbfYJjjWzvF53mqHVULa"),
("Bad Day","Darwin Deez","7hUuGmq5C0AlB4X58TrQ3e"),
("Run","Delta Rae","1G2y3ckwnDX4IOiemPOXEW"),
("1957","Milo Greene","08cXy6KUizaAelYXtcew3w"),
("Kisser","Step Rockets","419qOkEdlmbXS1GRJEMntC"),
("Paper Planes","East of Avenue","3O8FEh6DtlCUPRENPuhjHo"),
("Bigger Than Love (feat. Aimee Mann)","Benjamin Gibbard","1Cy7Naa54d9lWFSOXLGRow"),
("At Home","Crystal Fighters","3dXNrqnhNUPdrkvnj8TjvX"),
("Tompkins Square Park","Mumford & Sons","54oFXvBXWRGYRN88zjFKkH"),
("Bad Self Portraits","Lake Street Dive","4FGmmkujpwdkexqLobrp80"),
("It's Nice to Be Alive","Ball Park Music","7t0HMbsYInj7dfdA05UVJc"),
("Easy Way (Acapella)","For The Foxes","6VB2nPWSNl0JeCREEJ2vdF"),
("The John Wayne","Little Green Cars","460n97wRvhCNU4OVgZyM0V"),
("#88","Lo-Fang","1jjwFHRnfgBTJ049RJz8CQ"),
("First","Cold War Kids","3omXshBamrREltcf24gYDC"),
("I Always Knew","The Vaccines","15xyQQhsJfqUT1OVWmAKSN"),
("Better Days","Edward Sharpe & The Magnetic Zeros","2JCBER0TK8Of3EZ4yB2Y3Q"),
("All Will Be Well","Gabe Dixon","64rMBgXnYB3zU2oOvlxrc2"),
("Bright Whites","Kishi Bashi","6yt0j9NLA4s46AWkyHORVb"),
("Home","Dan Croll","2DYlCu6ENt9HzutTsHtYxe"),
("New Soul","Yael Naim","476JcJ3TpAuCOlGdCmomGm"),
("Brothers","Penny and Sparrow","3i9tuE2ltSIY3tmKhcoJB5"),
("Shots & Squats","Vigiland","5nIrdpo8eXQU3YgZelEXkd"),
("Jesu, Joy Of Man's Desiring (feat. Lili Haydn)","Josh Groban","5Re2wAhF2NFiYRLtnaOW3u"),
("Dance With Me","Ra Ra Riot","482nc1OVq3aK12gyW0Y6fV"),
("Darlin'","Houndmouth","2Dmw4LdpDKYFjKZ7hj1XAh"),
("Otis","Houndmouth","2Bc6YYxUPKoutpNdJgZGB4"),
("La Vie En Rose","Various Artists","36dRGk4xB4VlCdaB0eagnH"),
("Jackie and Wilson","Hozier","0PywzrV955BnXDC8FHAf0n"),
("Silhouettes","Colony House","612JlaWJl5l6VIrcBck5QB"),
("Maps","The Front Bottoms","5bsifWmUkQPnXXweW6Cx5u"),
("Let Somebody Love Me","David Ruffin","5CwUspqybw82s2LhSQD6Bn"),
("Furr","Blitzen Trapper","6n1zT8W5EaIYvWIT2DyROL"),
("Stuck In My Id","Reptar","6x1p8NLwIYd9PFaTU9LQON"),
("Naive","The Kooks","29XbgaYB4Hs8vlLmpzkRgj"),
("Somebody","Jukebox The Ghost","3DvZZTxVrDHyiFkEXTJR7A"),
("Mr. Pitiful","Matt Costa","3CeGVMZcCWSSCdOfcaHJnd"),
("Never Coming Down","Various Artists","4h1xcQgFlJyL2EpAIv5ont"),
("Coat of Armour","George Ezra","3IUEZsFIQv3QbE5K15SbJu"),
("Beware The Dog","The Griswolds","3KIIwkf6lNwJqLcx6GUIzr"),
("Rollercoaster","Bleachers","12bU7EsDacFu3ToZtB0ZQH"),
("Nothing It Can","Helios","4YEKwC3ipNg9LdR02OL8h2"),
("Dancing On Quicksand","Bad Suns","42ADpNS02UiRbRGyRYypFS"),
("Cardiac Arrest","Bad Suns","6zQyu8L8yUuJkl6LbQ6iKU"),
("Lay Your Love Down - Single Version","Wolf Gang","3yfkMsgfx3AigAmwIKSsLD"),
("Good As New","Vacationer","4IiLUcJ9MOMXMGNv9zXxY1"),
("Sleep Away","Bob Acri","5YHPH0wpc5IMqNNrbN3JMm"),
("The Mother We Share","CHVRCHES","3PvzvltQZLIKk9YgoMP3Yq"),
("Roman","Housse de Racket","1yb35WfP1wdOnSfSGDxWUY"),
("Miracle","Ghost Beach","5xgYhiAeoVbuFG2WJ98OSe"),
("Escapee","Architecture In Helsinki","4fazeTpTqcao38J8Zro9Pg"),
("Departures","Silverstein","7gcLtVIc2DFArRR40jS22T"),
("Oh Lord","Foxy Shazam","5iJU96441eAZ2VdWgxdyJa"),
("High","Young Rising Sons","4gTwPFGhIIlYtlo59jbVUB"),
("King Of The World","Young Rising Sons","4GuzyfGbR2y4L65ONTw1dk"),
("Turnin'","Young Rising Sons","7om9AA7nbASF0vzS2u5cDz"),
("Red & Gold","Young Rising Sons","1AamNShZqArJpaZMu6wW76"),
("If You Believe","Blues Saraceno","41e2Y9CEHcQ1lMX2l3dtt7"),
("My Type","Saint Motel","2Iq6HhIquO7JKr0KfTNLzU"),
("Geronimo","Sheppard","19cL3SOKpwnwoKkII7U3Wh"),
("Numb / Encore","JAY Z","5sNESr6pQfIhL3krM8CtZn"),
("Mexico","Jump Little Children","5gNtIEGsI3EqAgApSjqSk1"),
("Lost Stars","Various Artists","1cPtMErymxlrj7pssAB03r"),
("Dear Avery","The Decemberists","1uy8SZx78GLnVVaeBKgYVk"),
("June Hymn","The Decemberists","1bvERTuePaoVjQ3NpJq9aH"),
("The Crane Wife 3","The Decemberists","0IwXp8V7wgFCIthRh2z8Ot"),
("Riptide","Vance Joy","3JvrhDOgAt6p7K8mDyZwRd"),
("Monsters","Timeflies","4B7m32eXNZn28idq40sLif"),
("Love","American Authors","63jtv6OVPH2SPb03icmiVo"),
("I'm Ready","AJR","02ILwrgX3DDx9mclP2EI41"),
("Lloro Por Ti - Remix","Wisin & Yandel","5MTkTvxBmpkE1OGMu2mYlD"),
("Only Love","Ben Howard","2uhEKg8kIzpdvz4gyy6x8W")

]

pickle.dump(songList, open("songList.txt", "wb"))
